### ISSUE TITLE
Setup auth - login

### ISSUE THREAD

**Issue by ervinismu** [ervinismu/tulis#1]
UAC : 
- Login using email and password
- Logout

**Comment by ervinismu** [comment]
can you solved this issue issue @arifikhsan ?

**Comment by ervinismu** [comment]
Resolved with this Pull Request [#2 ](https://github.com/ervinismu/tulis/pull/2)

**Comment by arifikhsan** [comment]
> can you solved this issue @arifikhsan ?

no @ervinismu
